### ISSUE TITLE
Access to Seasonal Info

### ISSUE THREAD

**Issue by rweldon0828** [buffbears/Weatherscan#11]
Is there any seasonal info yet out there, like the Golf or Travel forecast? Just wondering!

**Comment by AnimeFanatic459** [comment]
as of now there's no golf, garden, ski, beach, travel, traffic or international segments.

**Comment by buffbears** [comment]
Seasonal slides will come in a future update.

**Comment by Galaga81** [comment]
Looking forward to the beach, ski, garden segments (in that order) 👍
