### ISSUE TITLE
Emulator gets stuck at slide

### ISSUE THREAD

**Issue by brenden7158** [buffbears/Weatherscan#13]
If the emulator runs for a while it will get stuck on a slide and display nothing but the background gradient.

**Comment by buffbears** [comment]
I need an error message, or I need to know what slide it freezes on to fix.

**Comment by brenden7158** [comment]
city slide, the main one

**Comment by buffbears** [comment]
I still need an error message or something to go off of.

**Comment by buffbears** [comment]
Any update on this?
