### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by rweldon0828** [buffbears/Weatherscan#17]
When I installed the new update, I felt like I went back a generation of Weatherscan. All I am getting now is older logos, and nothing seems to be new.
![Capture](https://user-images.githubusercontent.com/69129972/183315092-cbaf3cd2-4124-4e60-a93d-401b121cd9e3.PNG)

**Comment by Galaga81** [comment]
This version uses config.js to change the iconSet to 2007 or 2010 (2007 is the default) so maybe that's why it looks older? Change that to 2010 and you'll see those weather icons. The International and Travel segments are new in this version.
