### ISSUE TITLE
Now airports marquee bugs when only 1 airport is in newweathermanager

### ISSUE THREAD

**Issue by brenden7158** [buffbears/Weatherscan#18]
the marquee will bug when there is only one airport in main airports and will duplicate 6 times in the marquee
![image](https://user-images.githubusercontent.com/38764606/183416607-8db43630-82f6-4e3c-b7ab-c567e67ebdb2.png)

**Comment by buffbears** [comment]
I will look into this.

**Comment by brenden7158** [comment]
@buffbears update, it appears that it happens regardless of there being 1 airport or multiple, it will still duplicate them a few times

**Comment by brenden7158** [comment]
https://github.com/buffbears/Weatherscan/issues/22
this bug is linked to this too
it will keep duplicating which causes it to wrap
