### ISSUE TITLE
Safari graphic glitch in intros to Airports, Health, International, Travel

### ISSUE THREAD

**Issue by Galaga81** [buffbears/Weatherscan#19]
![Screen Shot 2022-08-08 at 8 50 02 AM](https://user-images.githubusercontent.com/110785484/183422660-b1d8cfbb-0592-4fc7-bcb6-27f43c316812.png) The bottom left curve piece is out of whack in Safari. Doesn't seem to do this in Chrome.

**Comment by brenden7158** [comment]
i had this issue on firefox

**Comment by Galaga81** [comment]
I found the fix. The order of the -webkit versions of the masks matter.
weatherscan.css
.info-slide .accent.ix
  mask-size:200% 100%;
  -webkit-mask-size:200% 200%;
  mask-position: 0% 100%;
  -webkit-mask-position: 0% 100%;
   mask-repeat: no-repeat;
  -webkit-mask-repeat: no-repeat;

**Comment by buffbears** [comment]
Ah I see, web-kit does things different.
I will implement this.

**Comment by buffbears** [comment]
Fixed.
