### ISSUE TITLE
marquee1 bug

### ISSUE THREAD

**Issue by brenden7158** [buffbears/Weatherscan#22]
![image](https://user-images.githubusercontent.com/38764606/183740873-99866716-5f00-439c-a654-a99095808c01.png)
https://user-images.githubusercontent.com/38764606/183741069-64326d59-01bb-4d74-bcd8-92a21086e62f.mp4

**Comment by buffbears** [comment]
I will investigate.

**Comment by buffbears** [comment]
I think I fixed this. I will close once I am able to confirm.
