### ISSUE TITLE
Air Quality - More Pollutants

### ISSUE THREAD

**Issue by Galaga81** [buffbears/Weatherscan#25]
I found these in the API, PM was displayed as Fine Particulates (plural)...

for newweathermanager.js

weatherInfo.airquality.primarypolute = (airqualitydata.globalairquality.primaryPollutant).replace('PM10','Fine Particulates').replace('PM2.5','Fine Particulates').replace('O3','Ozone').replace('CO','Carbon Monoxide').replace('NO2','Nitrogen Dioxide').replace('SO2','Sulfur Dioxide')

**Comment by buffbears** [comment]
Do you have good evidence to back up the other replacements?

**Comment by Galaga81** [comment]
the phrases are listed in the table here:
https://docs.google.com/document/d/1rcYHmIaGKtiINuEPJXGMWU5OEntPf2i0U8BBO8clmtQ/edit
