### ISSUE TITLE
Bug - Simulator Keeps Refreshing "Change Detected"

### ISSUE THREAD

**Issue by ihadtocreateastupidaccount** [buffbears/Weatherscan#26]
Whenever I start the emulator up it spam refreshes, and the terminal keeps saying "change detected

https://user-images.githubusercontent.com/111042084/184078111-9ccbbabb-f3d6-4693-9c22-d419305e37ae.mov

<img width="583" alt="Screen Shot 2022-08-11 at 1 41 45 AM" src="https://user-images.githubusercontent.com/111042084/184078123-34d0b40c-1aee-4e31-9f2d-984beaab20ed.png">
"

**Comment by rweldon0828** [comment]
Did you try to install Visual Studio Code for Mac? Typically I don't run the emulator in MacOS Terminal.

**Comment by buffbears** [comment]
Node.js should hopefully be using html-server instead of live-server.
