### ISSUE TITLE
Background change

### ISSUE THREAD

**Issue by ricardo636** [buffbears/Weatherscan#27]
Hi folks!. It's not a problem, rather it's a question about changing the background when the simulator starts. I want to change the buildings background to a neighborhood background. how can i change it? Thank you.

![Slide2](https://user-images.githubusercontent.com/101176805/184100113-a46ea63b-addf-48bd-bd08-2688b61ee6cd.jpg)

**Comment by GabeGitHub123** [comment]
Wow.

**Comment by buffbears** [comment]
I can add this in as a config option

**Comment by MapGuy11** [comment]
This is added in the config. Please self-host.
