### ISSUE TITLE
Map issues outside of US teritory

### ISSUE THREAD

**Issue by Live-OnTropics** [buffbears/Weatherscan#29]
If I try to view the emulation for any area outside of the US, other cities on the map do not appear except the city I am viewing the emulation for.  It was not an issue before the addition of travel and international forecasts. Also, the province borders seem to have vanished for any territory outside of the US. This is an example for Berlin, Germany.
![image](https://user-images.githubusercontent.com/73486481/185735169-3c094fd7-f826-490d-96ce-0c06c8a41224.png)

**Comment by buffbears** [comment]
International locations are not fully supported.
