### ISSUE TITLE
1998-2006 WeatherSTAR XL Icons and 2005-2006 Weatherscan Backgrounds/Graphics

### ISSUE THREAD

**Issue by malekmasoud** [buffbears/Weatherscan#30]
Here are my contributions to this project, both regarding the old classic (September 27, 2003-December 12, 2006) era of the Weatherscan Intellistar.

1998-2006 WeatherSTAR XL Icons
https://drive.google.com/file/d/1dkHbVmqYoI2hTSl5i1Y7M0ISyrFHA78B/view?usp=sharing

2005-2006 Weatherscan Backgrounds & Graphics
https://drive.google.com/file/d/1jVNChfTgSJKzMI6KULA7r0UM9m7g-Evy/view?usp=sharing

**Comment by Galaga81** [comment]
Nice work!

**Comment by malekmasoud** [comment]
> 

Well, thank you! 😉

**Comment by malekmasoud** [comment]
<img width="113" alt="blueradarcover" src="https://user-images.githubusercontent.com/25880200/186503641-569c3df4-c42e-49cf-b70a-d24f0cbd1da8.png">
Oh, and I almost forgot something! Here's the blue radar cover (for when we either go to severe weather mode and/or have any radar issues/outages) to go along with the other 2005-2006 Weatherscan background images.

**Comment by buffbears** [comment]
With the recent conversion to sprites for icons, it will take a minute to implement but I can get it implemented.
