### ISSUE TITLE
Health Tips Not Rotating

### ISSUE THREAD

**Issue by Galaga81** [buffbears/Weatherscan#31]
1. Health Tip always shows the hot car tip (summertip). The var tipidx always gets reset back to 0 when it loops.

2. How about adding randomness instead? Tested and works:
let summertipidx = Math.round(Math.random() * (summertips.length-1));
let wintertipidx = Math.round(Math.random() * (wintertips.length-1));

Open them like this:
$('.' + summertips[summertipidx]).show();
$('.' + wintertips[wintertipidx]).show();

Then close them like this so they don't pile up:
$('.' + summertips[summertipidx]).hide();
$('.' + wintertips[wintertipidx]).hide();

**Comment by buffbears** [comment]
I'll work on this some more, but I don't want to do it randomly as that does not repersent the real behavior.

**Comment by buffbears** [comment]
Fixed in latest update.
