### ISSUE TITLE
Documentation Clarification: Requirements

### ISSUE THREAD

**Issue by nbgibson** [buffbears/Weatherscan#32]
Per the README, Weatherscan requires mapbox.com and weather.com API keys to function properly. However, as best I have been able to determine, weather.com does not have a public API or at least does not detail one on their site. If this is the intended website, can you please alter the README to link to their API info?

**Comment by philliml74** [comment]
I am afraid that I am in the same boat.  I couldn't find an API for weather.com.  With mapbox.com, it looks like there are several APIs to pull from.  It would be nice to see a link the API required.

**Comment by lightmaster** [comment]
https://github.com/buffbears/Weatherscan/blob/79fb13dd51b34db351aa149ae9b71aca29c88460/webroot/js/newweathermanager.js#L98

It definitely requires a weather.com api key, just not sure how to get one

**Comment by lightmaster** [comment]
https://developer.ibm.com/blogs/call-for-code-the-weather-company-and-you/

**Comment by nbgibson** [comment]
I saw that as well, but the documentation states it's free only so long as you're participating in their challenge/program. I'm sure you can just sign up and go to town, but I doubt that would be a long term viable path forward.

**Comment by mlfreeman2** [comment]
I have a weather station uploading to Weather Underground, so they let me have a contributor API key...and their documentation tells me to hit api.weather.com.

If you have a Weather Underground station, that API key may be enough to get you working. 
I'll probably try eventually, but I'm not sure when.

**Comment by MapGuy11** [comment]
tsk tsk inspect element on wunderground.com

**Comment by nbgibson** [comment]
Hold a minute there, your comment just proves my initial point. The readme is incorrect/insufficient as is and needs to be corrected to:
1. Change weather.com references to wunderground.com
2. Include the inspect method you've mentioned in similar issue items 

Expansion on the inspect method would be appreciated as well.

**Comment by MapGuy11** [comment]
> Hold a minute there, your comment just proves my initial point. The readme is incorrect/insufficient as is and needs to be corrected to:
> 
> 1. Change weather.com references to wunderground.com
> 2. Include the inspect method you've mentioned in similar issue items
> 
> Expansion on the inspect method would be appreciated as well.

No they are the same API I was just trying to help get the API and that is one easy way to do it. We will not add this as we do not distribute the API you just need to know where to look.

**Comment by lightmaster** [comment]
So just to be clear (not at computer to test), a wunderground API key will work for this where it calls the Weather.com API, right?

**Comment by nbgibson** [comment]
@lightmaster Hey, you may be interested in this: https://openthings.freshdesk.com/support/solutions/articles/5000017485-getting-a-weather-underground-wu-api-key

Seems like you can just create a "ghost" device and go about your business. No need for getting all webdev about it.

**Comment by lightmaster** [comment]
@nbgibson Thanks, but I've already got a Wunderground API key from my weather website, just didn't know they had merged the Wunderground and Weather.com APIs on the server side.
