### ISSUE TITLE
Headless output to ffmpeg?

### ISSUE THREAD

**Issue by devenator** [buffbears/Weatherscan#33]
Hi, 

does someone know an easy way to render this to a videostream? I searched long, but all solutions eighter are OBS, which requires X11, or uses something like phantomjs to generate jpeg's, which is unusable for Weatherscan...

**Comment by Cellivar** [comment]
Could you use XVFB and connect to it from ffmpeg? Or whatever else you're using. 

https://gist.github.com/akutz/66c1ab27f0d26ff2e33a

https://stackoverflow.com/a/67092653/1309423
