### ISSUE TITLE
can you switch to openweather instead?

### ISSUE THREAD

**Issue by merrychrishna** [buffbears/Weatherscan#35]
can you let us use open weather instead? the api keys you recommended require too much personal info and a credit card even though it says its free.

i think openweather would be a lot better

The API key is all you need to call any of our weather APIs. Once you sign up using your email, the API key (APPID) will be sent to you in a confirmation email. Your API keys can always be found on your account page, where you can also generate additional API keys if needed.

[How to start to work with Openweather API - OpenWeatherMaphttps://openweathermap.org › appid](https://openweathermap.org/appid#:~:text=The%20API%20key%20is%20all,additional%20API%20keys%20if%20needed.)
[About featured snippets](https://www.google.com/url?url=https://support.google.com/websearch?p%3Dfeatured_snippets%26hl%3Den-US&rct=j&q=&esrc=s&usg=AOvVaw185ES_DZIoacbenypeQ03C&hl=en&sa=X&ved=2ahUKEwiT_Ymzm-X6AhXFrYkEHVWrAMMQrpwBegQIDBAC)
•

**Comment by merrychrishna** [comment]
youre weather site you linked to does not have an api key anywhere. i read it must be weather underground which wants a credit car and so does weather maps
. i think you need to simplify the whole process a lot more with simpler docs.

**Comment by MapGuy11** [comment]
No, this project uses the old IBM/TWC API as Weatherscan does. That would be a complete rewrite which is not in the cards right now. Tsk Tsk if you can't find the API keys do inspect element network on wunderground.com
