### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by ricardo636** [buffbears/Weatherscan#4]
I have a problem. When I open after install, I get an empty page.
![image](https://user-images.githubusercontent.com/101176805/157558320-9982f4ac-1651-4bc2-b005-cb1dab7b6e4b.png)

**Comment by ZeastTV** [comment]
did you put the API keys in secrets.js?

**Comment by MapGuy11** [comment]
> did you put the API keys in secrets.js?

Yeah that is his issue. Because that is the default showing when no API Keys are put in.

**Comment by ricardo636** [comment]
How i can get those api keys?

**Comment by MapGuy11** [comment]
> How i can get those api keys?

You can find them in earlier version from TWCBranden or know someone who has them we do not give out API Keys anymore.

**Comment by buffbears** [comment]
You need secrets.js
