### ISSUE TITLE
Intro Image config suggestion

### ISSUE THREAD

**Issue by AnimeFanatic459** [buffbears/Weatherscan#43]
![Screenshot (121)](https://user-images.githubusercontent.com/73317043/203486594-bac17605-4ed4-4ad1-8537-b4935dd49b46.png)
I think there should be a way to change this image in the config where every other config is instead of changing it in the CSS.

**Comment by Nacroni** [comment]
In "config.js", there is a way to set the `corebackground` to `forest`, `mountain`, `city`, `buildings`, `neighborhood`, `southwest`, and `ocean`. You _will_ have to clone the git repo via `$ git clone https://github.com/buffbears/Weatherscan/`. Or, you can use `backgroundURL` to a background image stored in the server.
