### ISSUE TITLE
No Radar Locations

### ISSUE THREAD

**Issue by rweldon0828** [buffbears/Weatherscan#44]
There is no locations showing up on the radar. All it's showing is a blank map other than with the outline of the satellite image. It was working for months but one day it just stopped!

**Comment by rweldon0828** [comment]
![Screenshot_20230209_074013](https://user-images.githubusercontent.com/69129972/217971290-64c507f1-a7a4-40bd-b4b4-6a37a9a8a150.png)

**Comment by Nacroni** [comment]
Are you using weatherscan.net or are you using a git clone?

**Comment by AnimeFanatic459** [comment]
this is because Goldblaze is moving away from mapbox I think.

**Comment by Nacroni** [comment]
> this is because Goldblaze is moving away from mapbox I think.

On the Weather Ranch discord, they said
[> `@here` I deleted my other mapbox key which was needed for some portions of the map. Only boundaries and labels are gone, radar and the basemap still work as usual. This will be fixed soon.](https://discordapp.com/channels/901963652649848892/971946393092628480/1054520638909452298)
They've just disabled it temporarily due to overusage by another client.

**Comment by rweldon0828** [comment]
> Are you using weatherscan.net or are you using a git clone?

I was using weatherscan.net at the time. But even with gitclone it doesn't function properly.

**Comment by rweldon0828** [comment]
> > this is because Goldblaze is moving away from mapbox I think.
> 
> On the Weather Ranch discord, they said [> `@here` I deleted my other mapbox key which was needed for some portions of the map. Only boundaries and labels are gone, radar and the basemap still work as usual. This will be fixed soon. They've just disabled it temporarily due to overusage by another client.](https://discordapp.com/channels/901963652649848892/971946393092628480/1054520638909452298)

For some reason I can see the announcement page on my discord. I think they have to invite me to it.

**Comment by MapGuy11** [comment]
> > > this is because Goldblaze is moving away from mapbox I think.
> > 
> > 
> > On the Weather Ranch discord, they said [> `@here` I deleted my other mapbox key which was needed for some portions of the map. Only boundaries and labels are gone, radar and the basemap still work as usual. This will be fixed soon. They've just disabled it temporarily due to overusage by another client.](https://discordapp.com/channels/901963652649848892/971946393092628480/1054520638909452298)
> 
> For some reason I can see the announcement page on my discord. I think they have to invite me to it.

YOu never agreed to our terms in the discord, therefore, cannot see anything else.
