### ISSUE TITLE
Weatherscan not functioning

### ISSUE THREAD

**Issue by TheGoldDiamond9** [buffbears/Weatherscan#48]
![Screenshot (262)](https://user-images.githubusercontent.com/116307221/221330403-d248847b-b05b-4ddb-aafc-0e03e121f3e9.png)
When I put the mapbox api key into the  mapboxg1.accessToken code line in the radar.js file and click save and restart the emulation the emulation gets stuck on this screen.

**Comment by Trent10598** [comment]
Aren't the keys supposed to just be put into the config file only?
