### ISSUE TITLE
cors.js

### ISSUE THREAD

**Issue by ZeastTV** [buffbears/Weatherscan#5]
i have the new js file downloaded and in the right folder, but i recieve a "MODULE_NOT_FOUND" code
![image](https://user-images.githubusercontent.com/101219601/157802660-bc868d6d-d813-4cbf-984e-fcd7a9c3db8b.png)

**Comment by ZeastTV** [comment]
I tried a fresh install as a fix incase i made a mistake myself and this happened
![image](https://user-images.githubusercontent.com/101219601/157806428-986c578b-7311-4f04-abd0-7a1b0002e44b.png)

**Comment by buffbears** [comment]
Required dependencies should now be included. Update and try with that.

**Comment by ZeastTV** [comment]
> 

Alright thank you

**Comment by buffbears** [comment]
I will close this issue as, others have confirmed that it has been fixed.
