### ISSUE TITLE
ccticker not displaying cities from config.js, showing random cities from across the US instead

### ISSUE THREAD

**Issue by TheRealBrayden** [buffbears/Weatherscan#50]
I have edited my config.js to show a list of cities close to me, under marqueeCities. 
However, instead of displaying those cities, the ccticker shows forecasts for random cities from all different states, a few being Fargo, Tempe, Chicago, and Minneapolis. Not sure if this is related, but I also edited the mainairports list under newweathermanager.js to only include Philadelphia International Airport. I erased all the other airports.
How can I get the ccticker to show the list of cities I inputted and not random ones? Thanks.

**Comment by MapGuy11** [comment]
API issue
