### ISSUE TITLE
How to get weather.com api?

### ISSUE THREAD

**Issue by vivbyte** [buffbears/Weatherscan#51]
I have been searching all night for the weather.com api and I have found absolutely zero info on the matter. Can someone provide me a link to the api page so I can run this locally?

**Comment by Nacroni** [comment]
Might be [https://www.ibm.com/products/environmental-intelligence-suite/apis](https://www.ibm.com/products/environmental-intelligence-suite/apis) or [https://developer.ibm.com/components/weather-company/apis/](https://developer.ibm.com/components/weather-company/apis/).
