### ISSUE TITLE
New radar issues.

### ISSUE THREAD

**Issue by TrueHerobrine** [buffbears/Weatherscan#52]
Love the new radar, with the ability to actually see cities and county lines, but no precipitation appears on the map, and the emulator is stuck on the radar screen.
![image_2023-07-19_185712807](https://github.com/buffbears/Weatherscan/assets/69488295/6ae940aa-f5e7-4f70-93c3-fdf44702c391)

**Comment by MapGuy11** [comment]
BEING FIXED

**Comment by ryanginn** [comment]
Still getting this issue.
