### ISSUE TITLE
Radar dots for cities seem to be roughly 10 pixels below the actual city.

### ISSUE THREAD

**Issue by TrueHerobrine** [buffbears/Weatherscan#54]
Here's an example, with the red indicating roughly where the dot should be placed:
![Opera Snapshot_2023-07-21_220305_weatherscan net](https://github.com/buffbears/Weatherscan/assets/69488295/b7f5e565-799e-4553-b55b-a333a413ec57)

An interesting thing to note is that this only affects the mini radar at the bottom left, and not the large radar used in the local forecast segment.

**Comment by buffbears** [comment]
Mapbox issue will be fixed in the recode.
