### ISSUE TITLE
Mini radar doesn't update and Local Doppler Radar freezes after a while

### ISSUE THREAD

**Issue by fdezwonders** [buffbears/Weatherscan#69]
2 issues in 1:

1) The mini radar displayed in the bottom right corner does not update. Below are screenshots at the end of the radar loop. They were both taken 2 hours apart (same emulation run). Time is included for reference.
![Mini Radar loop 6pm](https://github.com/user-attachments/assets/71078f44-9912-41cd-99da-669866d85851)
![Mini Radar loop 8pm](https://github.com/user-attachments/assets/b7045084-f00b-4781-8bec-fba355a328ec)

2) After a while of running the emulation, the Local Doppler Radar freezes on the first frame. Videos are attached below with time for reference.
![Radar beginning](https://github.com/buffbears/Weatherscan/assets/173704271/1c67aa42-df14-4517-a319-416dc04e382e)
![Radar later](https://github.com/buffbears/Weatherscan/assets/173704271/60570739-3701-45f7-ad7f-8a931740aaac)

Ran using weatherscan.net.

**Comment by MapGuy11** [comment]
Yes this is a known issue please use OBS Browser with an auto refresher.
