### ISSUE TITLE
Category transitions lag browser heavily

### ISSUE THREAD

**Issue by Squiddu** [buffbears/Weatherscan#70]
![image](https://github.com/user-attachments/assets/c666bc67-6d96-4958-916d-87952f6d3b19)
These screens lag my browser heavily whenever on screen. 

Some shoddy experimenting seems to imply the scrolling `weatherscan` text may be the issue. Perhaps due to using a very long string of text instead of infinite scrolling?

**Comment by fdezwonders** [comment]
This is not happening to me, this is probably an issue of computer power. The weatherscan text scrolling could be the issue, but in my testing (video attached) on a M1 MacBook, this does not happen to me. Try freeing up RAM or something idk

Also, the video below was recording on Google Chrome version 126.0.6478.127 (Official Build) (arm64)
I also tested this on Safari and it didn't lag either.

https://github.com/user-attachments/assets/1ac6ca33-c555-4a27-bfb3-a9523289b3a9

**Comment by Squiddu** [comment]
Don't think so.

LibreWolf Firefox v127.0.2-2 (Win x86-64), Hardware acceleration disabled
Intel Core i5-10400F
NVIDIA GeForce RTX 3060
48GB RAM, 2.1GHz

**Comment by fdezwonders** [comment]
I'm guessing your issue is having hardware acceleration disabled, which can slow down some websites, including weatherscan.net.
Try enabling Hardware acceleration (sometimes called Graphics acceleration) in your browser, and see if that fixes it.

**Comment by Squiddu** [comment]
For whatever reason, it does fix it, but the browser has a complete fit over it and it spits out random visual glitches of the page so either way I'm screwed

**Comment by fdezwonders** [comment]
@Squiddu - Hmm, glad to hear that it does fix it.
> but the browser has a complete fit over it and it spits out random visual glitches of the page

That shouldn't be happening, if able to, try to record a video if that happening, but with what I have, I would recommend trying the following:

1) If running a local instance, try going to weatherscan.net, if running on the weatherscan.net website, try running a local instance. It might make a difference.
2) A extension could be interfering with the website, try running it in a Private Window.
3) Firefox could also be messing with the website, try using a Chromium browser (like Google Chrome or Arc).

Hopefully that fixes the issue! 

(also, after some digging, the scrolling text is just `weatherscan` copy and pasted 20 times, then set to scrolling. the text `weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan  weatherscan` scrolling probably isn't what is causing the issue)

**Comment by Squiddu** [comment]
@fdezwonders It seems that Firefox/LibreWolf was the issue. After changing certain suggested flags that did nothing, switching over to Ungoogled Chromium seemed to work completely fine, no graphical glitches or lagging. Seems like this has been an issue for Firefox for a while now :(

**Comment by fdezwonders** [comment]
@Squiddu Great to hear the 3rd solution worked for you! You can probably close this issue now.
